id: P006693
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:17:04.700564
source_metadata:
  id: bdr:W14425
  title: དབུ་མ་ཀླུ་སྒྲུབ་དགོངས་རྒྱན་གྱི་དགག་པ།
  author: ''
  volumes:
    aa8c395602ba4d78b381e6ec69d93e6d:
      image_group_id: I1KG9840
      title: ''
      volume_number: 1
      total_pages: 210
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
